<?php

/**
 * Implementation of hook_menu()
 *
 * @return array
 */
function memory_cart_menu() {
    $items = array();

    // Ajax Callback intended to add in the cart the activity clicked when user is on a destination page
    $items['destinations/ajax/cart'] = array(
        'title' => 'Ajax callback',
        'page callback' => 'ajax_add_activity_to_cart',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    // Ajax Callback intended to send quotation ask
    $items['ajax/cart/quotation'] = array(
        'title' => 'Ajax callback',
        'page callback' => 'ajax_cart_send_user_quotation_ask',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function ajax_add_activity_to_cart(){

    global $base_url;

    $activity_nid = $_POST['actNid'];
    $activity_title = $_POST['actTitle'];

    $node_load = node_load($activity_nid);

    $reel_activity_title = field_get_items("node", $node_load, "field_activity_title");
    /*
    Check authenticity of the asked activity.
    If the title get by the nid isn't the same as the thumbnail title send by ajax,
    it will say that the user change either the nid either the title
    */
    if( $reel_activity_title[0]["value"] == $activity_title ){

        // Get the Destination field value of the activity
        $activity_field_img = field_get_items("node", $node_load, "field_img_activite");
        // Get the destination TID
        $activity_img_url = file_create_url($activity_field_img[0]["uri"]);

        // Get the pack title field value of the activity
        $activity_field_pack_title = field_get_items("node", $node_load, "field_title_prestation_base");
        // Get the pack title value
        $activity_pack_title = $activity_field_pack_title[0]["value"];

        $arrayCartActivity = array(
            "nid" => $node_load->nid,
            "title" => $activity_title,
            "image" => $activity_img_url,
            "packTitle" => $activity_pack_title,
        );

//        drupal_set_message("<pre>" . print_r($arrayCartActivity, true) . "</pre>");

        drupal_json_output($arrayCartActivity);
    }else{

        drupal_json_output("Les données demandées ne sont pas intègres");
    }
}

function ajax_cart_send_user_quotation_ask(){

  global $base_url;
  global $user;

  $destination_email = variable_get('global_parameter_email');
  $array_result_callback = array();

  if(!isset($destination_email)){

      $array_result_callback = array(
          "result_sentence" => "La demande de devis n'a pas abouti. Veuillez réessayer ultérieurement.",
          "is_success" => false
      );

      drupal_json_output($array_result_callback);
  }else{
      $cart_location = $_POST['location'];
      //$cart_date = $_POST['date'];
      $cart_departure_date = $_POST['departureDate'];
      $cart_return_date = $_POST['returnDate'];
      $cart_participants = ($_POST['participants'] != "") ? $_POST['participants'] : "Non spécifié";
      $cart_budget = $_POST['budget'];
      $cart_transport = $_POST['transport'];
      $cart_trip = $_POST['trip'];
      $cart_wish = ($_POST['wish'] != "") ? $_POST['wish'] : "Non spécifié";

      $cart_user_is_anonymous = $_POST['userIsAnonymous'];

//      drupal_set_message("Location : " . $cart_location);
//      drupal_set_message("Date : " . $cart_date);
//      drupal_set_message("Participants : " . $cart_participants);
//      drupal_set_message("Budget : " . $cart_budget);
//      drupal_set_message("Transport : " . $cart_transport);
//      drupal_set_message("Trip : " . $cart_trip);
//      drupal_set_message("Wish : " . $cart_wish);
//      drupal_set_message("User firstname : " . $cart_user_firstname);
//      drupal_set_message("User lastname : " . $cart_user_lastname);
//      drupal_set_message("User email : " . $cart_user_email);
//      drupal_set_message("User phone : " . $cart_user_phone);
//      drupal_set_message("Destination EMAIL : " . $destination_email);

      /* Start - E-mail body */
      $body =
        "DEMANDE DE DEVIS : " . "\n\n"
      ;

      if($cart_user_is_anonymous === true || $cart_user_is_anonymous === "true"){

          $cart_user_firstname = $_POST['userFirstname'];
          $cart_user_lastname = $_POST['userLastname'];
          $cart_user_email = $_POST['userEmail'];
          $cart_user_phone = $_POST['userPhone'];

          $body =
              $body .
              "---------------------------------------------------------" . "\n\n" .
              "Information sur l'utilisateur : " . "\n\n" .
              "Prénom : " . $cart_user_firstname . "\n" .
              "Nom : " . $cart_user_lastname . "\n" .
              "E-mail : " . $cart_user_email . "\n" .
              "Téléphone : " . $cart_user_phone . "\n\n"
          ;

      }else if($cart_user_is_anonymous === false || $cart_user_is_anonymous === "false"){

          $user_load = user_load($user->uid);

          $user_uid = ($user_load->uid != "") ? $user_load->uid : "Non spécifié";
          $user_name = ($user_load->name != "") ? $user_load->name : "Non spécifié";
          $user_email = ($user_load->mail != "") ? $user_load->mail : "Non spécifié";

          $body =
              $body .
              "---------------------------------------------------------" . "\n\n" .
              "Information sur l'utilisateur : " . "\n\n" .
              "UID : " . $user_uid . "\n" .
              "Nom : " . $user_name . "\n" .
              "E-mail : " . $user_email . "\n\n"
          ;
      }

      $cart_trip_sorted = [];

      for($i = 0; $i < sizeof($cart_trip) ; $i++){

        $cart_trip_sorted[$cart_trip[$i]["actDestination"]][$cart_trip[$i]["dayNumber"]][$cart_trip[$i]["activityType"]][$cart_trip[$i]["positionInDay"]]["actDestination"] = $cart_trip[$i]["actDestination"];
        $cart_trip_sorted[$cart_trip[$i]["actDestination"]][$cart_trip[$i]["dayNumber"]][$cart_trip[$i]["activityType"]][$cart_trip[$i]["positionInDay"]]["positionInDay"] = $cart_trip[$i]["positionInDay"];
        $cart_trip_sorted[$cart_trip[$i]["actDestination"]][$cart_trip[$i]["dayNumber"]][$cart_trip[$i]["activityType"]][$cart_trip[$i]["positionInDay"]]["activityType"] = $cart_trip[$i]["activityType"];
        $cart_trip_sorted[$cart_trip[$i]["actDestination"]][$cart_trip[$i]["dayNumber"]][$cart_trip[$i]["activityType"]][$cart_trip[$i]["positionInDay"]]["title"] = $cart_trip[$i]["title"];
        $cart_trip_sorted[$cart_trip[$i]["actDestination"]][$cart_trip[$i]["dayNumber"]][$cart_trip[$i]["activityType"]][$cart_trip[$i]["positionInDay"]]["nid"] = $cart_trip[$i]["nid"];
        $cart_trip_sorted[$cart_trip[$i]["actDestination"]][$cart_trip[$i]["dayNumber"]][$cart_trip[$i]["activityType"]][$cart_trip[$i]["positionInDay"]]["packTitle"] = $cart_trip[$i]["packTitle"];
        $cart_trip_sorted[$cart_trip[$i]["actDestination"]][$cart_trip[$i]["dayNumber"]][$cart_trip[$i]["activityType"]][$cart_trip[$i]["positionInDay"]]["actPrice"] = $cart_trip[$i]["actPrice"];

//        $cart_trip_sorted[$cart_trip[$i]["dayNumber"]][$cart_trip[$i]["activityType"]][$cart_trip[$i]["positionInDay"]]["actDestination"] = $cart_trip[$i]["actDestination"];
//        $cart_trip_sorted[$cart_trip[$i]["dayNumber"]][$cart_trip[$i]["activityType"]][$cart_trip[$i]["positionInDay"]]["positionInDay"] = $cart_trip[$i]["positionInDay"];
//        $cart_trip_sorted[$cart_trip[$i]["dayNumber"]][$cart_trip[$i]["activityType"]][$cart_trip[$i]["positionInDay"]]["activityType"] = $cart_trip[$i]["activityType"];
//        $cart_trip_sorted[$cart_trip[$i]["dayNumber"]][$cart_trip[$i]["activityType"]][$cart_trip[$i]["positionInDay"]]["title"] = $cart_trip[$i]["title"];
//        $cart_trip_sorted[$cart_trip[$i]["dayNumber"]][$cart_trip[$i]["activityType"]][$cart_trip[$i]["positionInDay"]]["nid"] = $cart_trip[$i]["nid"];
//        $cart_trip_sorted[$cart_trip[$i]["dayNumber"]][$cart_trip[$i]["activityType"]][$cart_trip[$i]["positionInDay"]]["packTitle"] = $cart_trip[$i]["packTitle"];
//        $cart_trip_sorted[$cart_trip[$i]["dayNumber"]][$cart_trip[$i]["activityType"]][$cart_trip[$i]["positionInDay"]]["actPrice"] = $cart_trip[$i]["actPrice"];

      }

      $final_cart_trip = [];

      foreach($cart_trip_sorted as $key=>$value) {

          // Sort array by day then by activity position in the day
          ksort($value);
          for($i = 0 ; $i < sizeof($value) ; $i++){
              ksort($value[$i]["activities"]);
          }

          $final_cart_trip[$key] = $value;
      }

//      // Sort array by day then by activity position in the day
//      ksort($cart_trip_sorted);
//      for($i = 0 ; $i < sizeof($cart_trip_sorted) ; $i++){
//        ksort($cart_trip_sorted[$i]["activities"]);
//      }

      $body_activities_info = "";
      $total_nb_city = 0;
      $totalDaysNb = 0;
      $totalNightsNb= 0;

      foreach($final_cart_trip as $key=>$value){

          $body_activities_info =
            $body_activities_info .
            "\n\n------------------------- Ville : " . $key . " -------------------------\n\n"
          ;

          $total_nb_city++;

          // Add transfer to the body e-mail
          if( !empty($value[1]["transfer"]) ){

              $body_activities_info =
                  $body_activities_info .
                  "Transfert - Aller : " . "\n" .
                  "   - Titre : " . $value[1]["transfer"][0]["title"] . "\n" .
                  "   - Pack : " . $value[1]["transfer"][0]["packTitle"] . "\n" .
                  "   - Prix : " . $value[1]["transfer"][0]["actPrice"] . "\n" .
                  "   - URL : " . $base_url . "/" . drupal_get_path_alias("node/" . $value[1]["transfer"][0]["nid"]) . "\n\n"
              ;
          }
          if( !empty($value[2]["transfer"]) ){

              $body_activities_info =
                  $body_activities_info .
                  "Transfert - Retour : " . "\n" .
                  "   - Titre : " . $value[2]["transfer"][0]["title"] . "\n" .
                  "   - Pack : " . $value[2]["transfer"][0]["packTitle"] . "\n" .
                  "   - Prix : " . $value[2]["transfer"][0]["actPrice"] . "\n" .
                  "   - URL : " . $base_url . "/" . drupal_get_path_alias("node/" . $value[2]["transfer"][0]["nid"]) . "\n\n"
              ;
          }

          // Add activities to the body e-mail

          for($i = 1 ; $i < sizeof($value) ; $i++){

              if( !empty($value[$i]["activities"]) || !empty($value[$i]["hosting"]) ){

                  $totalDaysNb++;

                  $body_activities_info =
                      $body_activities_info .
                      "\n\n" . "--- JOUR " . $i . " : " . "\n\n"
                  ;

                  for($j = 0 ; $j < sizeof($value[$i]["activities"]) ; $j++){

                      $body_activities_info =
                          $body_activities_info .
                          "Activité n°" . $value[$i]["activities"][$j]["positionInDay"] . " : " . "\n" .
                          "   - Titre : " . $value[$i]["activities"][$j]["title"] . "\n" .
                          "   - Pack : " . $value[$i]["activities"][$j]["packTitle"] . "\n" .
                          "   - Prix : " . $value[$i]["activities"][$j]["actPrice"] . "\n" .
                          "   - URL : " . $base_url . "/" . drupal_get_path_alias("node/" . $value[$i]["activities"][$j]["nid"]) . "\n\n"
                      ;
                  }

                  for($j = 0 ; $j < sizeof($value[$i]["hosting"]) ; $j++){

                      $totalNightsNb++;

                      $body_activities_info =
                          $body_activities_info .
                          "Hébergement : " . "\n" .
                          "   - Titre : " . $value[$i]["hosting"][$j]["title"] . "\n" .
                          "   - Pack : " . $value[$i]["hosting"][$j]["packTitle"] . "\n" .
                          "   - Prix : " . $value[$i]["hosting"][$j]["actPrice"] . "\n" .
                          "   - URL : " . $base_url . "/" . drupal_get_path_alias("node/" . $value[$i]["hosting"][$j]["nid"]) . "\n\n"
                      ;
                  }
              }
          }
      }

      $body_quotation_info =
          "---------------------------------------------------------" . "\n\n" .
          "Information sur la demande de devis : " . "\n\n" .
          "Lieu de départ : " . $cart_location . "\n" .
          "Date de départ : " . $cart_departure_date . "\n" .
          "Date de retour : " . $cart_return_date . "\n" .
          "Participants : " . $cart_participants . "\n" .
          "Budget : " . $cart_budget . "\n" .
          "Transport : " . $cart_transport . "\n" .
          "Wish : " . $cart_wish . "\n\n" .
          "---------------------------------------------------------" . "\n\n" .
          "Nombre total de ville : " . $total_nb_city . "\n" .
          "Séjour de " . $totalDaysNb . " jour(s) et " . $totalNightsNb . " nuit(s)" . "\n\n" .
          "---------------------------------------------------------" . "\n\n" .
          "Détails sur les activités souhaitées : \n\n"
      ;

      $body = $body . $body_quotation_info . $body_activities_info;
      /* End - E-mail body */

      // Mail's parameters
      $to = $destination_email;
      $from = $destination_email;

      // Subject of the mail
      $subject = "Memory - Demande de devis";

      // Call mail function
      $params = array(
        'subject' => $subject,
        'body' => $body,
      );

      if(drupal_mail('memory_cart', '10', $to, "fr", $params, $from)){

          $array_result_callback = array(
            "result_sentence" => "La demande de devis a été envoyé.",
            "is_success" => true
          );

          drupal_json_output($array_result_callback);
      } else {

          $array_result_callback = array(
            "result_sentence" => "La demande de devis n'a pas abouti. Veuillez réessayer ultérieurement.",
            "is_success" => false
          );

          drupal_json_output($array_result_callback);
      }
  }
}

/**
 * Implementation of hook_mail().
 *
 * A very simple hook_mail() implementation, for module "memory_cart".
 * This implementation expects to receive a $body, $subject, and $headers
 * inside the $params sent from drupal_mail(), rather than construct
 * those here in the hook.
 * @param $key
 * @param $message
 * @param $params
 * @see drupal_mail()
 */
function memory_cart_mail($key, &$message, $params) {
  switch ($key) {
    case '10':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
      break;
  }
}

/**
 * Implement hook_theme()
 *
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function memory_cart_theme($existing, $type, $theme, $path) {
    return array(
        'tpl_memory_cart' => array(
            'template' => 'tpl/memory_cart',
            'path' => drupal_get_path('module', 'memory_cart'),
            'variables' => array('infos' => NULL),
        ),
    );
}

/**
 * @return mixed
 */
function memory_cart_block_info() {

    $blocks['memory_cart'] = array(
        'info' => t('Memory cart'),
        'weight' => 1,
        'status' => 1,
        'region' => 'content',
        'visibility' => BLOCK_VISIBILITY_NOTLISTED,
        'pages' => 'admin/*\rmedia/*',
    );

    return $blocks;
}

/**
 * @param string $delta
 * @return array
 * @throws Exception
 */
function memory_cart_block_view($delta = '') {

    $block = array();

    switch ($delta) {
        case 'memory_cart':

            $is_user_logged_in = null;

            if(user_is_logged_in()){
              $is_user_logged_in = true;
            }else{
              $is_user_logged_in = false;
            }

            $data['is_user_logged_in'] = $is_user_logged_in;

            // Link the template
            $block['content']['#markup'] = theme('tpl_memory_cart', $data);

            // Link a css file
            $block['content']['#attached']['css'][] = array(
              'data' => drupal_get_path('module', 'memory_cart').'/css/memory_cart.css',
              'type' => 'file'
            );

            // Link a js file
            $block['content']['#attached']['js'][] = array(
                'data' => drupal_get_path('module', 'memory_cart').'/js/memory_cart.js',
                'type' => 'file'
            );

            break;
    }

    return $block;
}
