<?php

/**
 * Implementation of hook_menu()
 *
 * @return array
 */
function memory_blocks_menu() {
    $items = array();

    $items['admin/memory'] = array(
        'title' => t('Memory'),
        'description' => t('Memory - Tab'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('memory_blocks_admin_redirect'),
        'access arguments' => array('administer site configuration'),
        'type' => MENU_NORMAL_ITEM,
    );

    $items['admin/memory/social-networks-manager'] = array(
        'title' => t('Memory - Social networks list'),
        'description' => t('Memory - Social networks list manager'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('memory_blocks_admin_social_networks_list_form'),
        'access arguments' => array('administer site configuration'),
        'type' => MENU_NORMAL_ITEM,
    );

    $items['admin/memory/social-networks-manager/add'] = array(
        'title' => t('Add - Social network'),
        'description' => t('Add - Social network'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('memory_blocks_admin_social_network_add_form'),
        'access arguments' => array('administer site configuration'),
//        'type' => MENU_NORMAL_ITEM,
    );

    $items['admin/memory/social-networks-manager/social-network/%/edit'] = array(
        'title' => t('Memory - Social network'),
        'description' => t('Memory - Social network'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('memory_blocks_admin_social_network_form'),
        'access arguments' => array('administer site configuration'),
//        'type' => MENU_NORMAL_ITEM
    );

    $items['admin/memory/top-destinations-manager'] = array(
        'title' => t('Memory - Top destinations'),
        'description' => t('Memory - Top destinations manager'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('memory_blocks_top_destinations_admin_form'),
        'access arguments' => array('administer site configuration'),
        'type' => MENU_NORMAL_ITEM,
    );

    $items['admin/memory/top-activities-manager'] = array(
        'title' => t('Memory - Top activities'),
        'description' => t('Memory - Top activities manager'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('memory_blocks_top_activities_admin_form'),
        'access arguments' => array('administer site configuration'),
        'type' => MENU_NORMAL_ITEM,
    );

    $items['admin/memory/footer-manager'] = array(
        'title' => t('Memory - Footer'),
        'description' => t('Memory - Footer manager'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('memory_blocks_footer_admin_form'),
        'access arguments' => array('administer site configuration'),
        'type' => MENU_NORMAL_ITEM,
    );

    return $items;
}

function memory_blocks_init() {

    // If user is on destinations page, link css file
    if(preg_match("/^.*\/destinations\/.*$/", $_SERVER['REQUEST_URI'])){

        drupal_add_css(drupal_get_path('module', 'memory_blocks') . '/css/destination.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));
        drupal_add_js(drupal_get_path('module', 'memory_blocks') . '/js/destination.js', array('group' => JS_DEFAULT, 'every_page' => TRUE));
    }

    // If user is on activity page, link css file
    if(preg_match("/^.*\/product\/.*$/", $_SERVER['REQUEST_URI'])){

        drupal_add_css(drupal_get_path('module', 'memory_blocks') . '/css/activity.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));
    }

    // If user is on activity page, link css file
    if(preg_match("/^.*\/contact$/", $_SERVER['REQUEST_URI'])){

        drupal_add_css(drupal_get_path('module', 'memory_blocks') . '/css/contact.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));
    }

    // If user click on destinations tab, link css and js file
    if(preg_match("/^.*\/destinations$/", $_SERVER['REQUEST_URI'])){

        drupal_add_css(drupal_get_path('module', 'memory_blocks') . '/css/all-destinations.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));
        drupal_add_js(drupal_get_path('module', 'memory_blocks') . '/js/all-destinations.js', array('group' => JS_DEFAULT, 'every_page' => TRUE));
    }
}


/**
 * Implements memory_blocks_admin_redirect()
 */
function memory_blocks_admin_redirect(){
    drupal_goto("admin/Memory/social-networks-manager");
}

/**
 * @param $form
 * @param $form_state
 * @return mixed
 */
function memory_blocks_admin_social_networks_list_form($form, &$form_state) {

    $header = array(
        'id' => array('data' => t('id'), 'field' => 'msn.id'),
        'name' => array('data' => t('name'), 'field' => 'msn.name'),
        'url' => array('data' => t('url'), 'field' => 'msn.url'),
        'icon' => array('data' => t('icon'), 'field' => 'msn.icon'),
        'operations' => array('data' => t('Operations')),
    );

    $query = db_select('memory_social_networks', 'msn');
    user_build_filter_query($query);

    $count_query = clone $query;
    $count_query->addExpression('COUNT(msn.id)');

    $query = $query->extend('PagerDefault')->extend('TableSort');
    $query
        ->fields('msn', array('id', 'name', 'url', 'icon'))
        ->limit(50)
        ->orderByHeader($header)
        ->setCountQuery($count_query);
    $result = $query->execute();

    $destination = drupal_get_destination();

    foreach ($result as $social_network) {

        $options[$social_network->id] = array(
            'id' => $social_network->id,
            'name' => $social_network->name,
            'url' => $social_network->url,
            'icon' => $social_network->icon,
            'operations' => array('data' => array('#type' => 'link', '#title' => t('edit'), '#href' => "admin/memory/social-networks-manager/social-network/$social_network->id/edit", '#options' => array('query' => $destination))),
        );
    }

    $form['accounts'] = array(
        '#type' => 'tableselect',
        '#header' => $header,
        '#options' => $options,
        '#empty' => t('No social network available.'),
    );

    return $form;
}

/**
 * @param $form
 * @param $form_state
 * @return mixed
 */
function memory_blocks_admin_social_network_add_form($form, &$form_state){

    $form['social_networks']['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Nom'),
        '#weight' => 1,
    );

    $form['social_networks']['url'] = array(
        '#type' => 'textfield',
        '#title' => t('URL ou adresse e-mail'),
        '#weight' => 2,
    );

    $form['social_networks']['icon'] = array(
        '#type' => 'textfield',
        '#title' => t('Icône'),
        '#description' => t(
            'Choississez l\'icône représentant votre média sur : '.
            '<em>https://fontawesome.com/v4.7.0/icons</em>'.
            '<br> Puis renseigné le nom de l\'icône. '.
            '<em>Exemple : fa-facebook</em>'
        ),
        '#weight' => 3,
    );

    $form['social_networks']['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Valider'),
        '#weight' => 10,
    );

    $form['social_networks']['submit']['#submit'][] = 'memory_blocks_admin_social_network_add_form_submit';

    return $form;
}

/**
 * @param $form
 * @param $form_state
 * @throws Exception
 */
function memory_blocks_admin_social_network_add_form_submit($form, &$form_state){

    if(
        $form_state['values']['name'] == "" ||
        $form_state['values']['url'] == "" ||
        $form_state['values']['icon'] == ""
    ){
        drupal_set_message(t('Veuillez remplir toutes les informations.'));
    }else{

        db_insert('memory_social_networks')->fields(
            array(
                'name' => $form_state['values']['name'],
                'url' => $form_state['values']['url'],
                'icon' => $form_state['values']['icon'],
            )
        )
            ->execute();

        // Display a message saying that datas are set in database.
        drupal_set_message(t('Les données renseignées ont été enregistrées.'));
    }
}

/**
 * @param $form
 * @param $form_state
 * @return mixed
 */
function memory_blocks_admin_social_network_form($form, &$form_state){

    $fullUrl  = $_SERVER["REQUEST_URI"];
    $urlId = explode("/social-network/", $fullUrl)[1];
    $urlId = explode("/", $urlId)[0];

    $query = db_select('memory_social_networks', 'msn');
    $query->fields('msn', array('id', 'name', 'url', 'icon'));
    $query->condition('id', $urlId, '=');
    $results = $query->execute();

    foreach ($results as $result) {

        $form['social_networks']['id'] = array(
            '#type' => 'hidden',
            '#value' => $result->id,
        );

        $form['social_networks']['name'] = array(
            '#type' => 'textfield',
            '#title' => t('Nom'),
            '#default_value' => $result->name,
            '#weight' => 1,
        );

        $form['social_networks']['url'] = array(
            '#type' => 'textfield',
            '#title' => t('URL ou adresse e-mail'),
            '#default_value' => $result->url,
            '#weight' => 2,
        );

        $form['social_networks']['icon'] = array(
            '#type' => 'textfield',
            '#title' => t('Icône'),
            '#default_value' => $result->icon,
            '#description' => t('Choississez l\'icône représentant votre média sur : https://fontawesome.com/v4.7.0/icons'),
            '#weight' => 3,
        );

    }

    $form['social_networks']['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Valider'),
        '#weight' => 10,
    );

    $form['social_networks']['delete'] = array(
        '#type' => 'submit',
        '#value' => t('Supprimer'),
        '#weight' => 11,
    );

    $form['social_networks']['submit']['#submit'][] = 'memory_blocks_admin_social_networks_form_submit';
    $form['social_networks']['delete']['#submit'][] = 'memory_blocks_admin_social_networks_form_delete';

    return $form;
}

/**
 * @param $form
 * @param $form_state
 */
function memory_blocks_admin_social_networks_form_submit($form, &$form_state){

    db_update('memory_social_networks')
        ->condition('id', $form_state['values']['id'],'=')
        ->fields(array(
            'name' => $form_state['values']['name'],
            'url' => $form_state['values']['url'],
            'icon' => $form_state['values']['icon'],
        ))
        ->execute();

    drupal_set_message("Les changements ont été pris en compte.");
}

/**
 * @param $form
 * @param $form_state
 */
function memory_blocks_admin_social_networks_form_delete($form, &$form_state){

    db_delete('memory_social_networks')
        ->condition('id', $form_state['values']['id'], '=')
        ->execute();

    drupal_set_message("Le média a été supprimé.");
}

/**
 * Implement hook_theme()
 *
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function memory_blocks_theme($existing, $type, $theme, $path) {
    return array(
        'tpl_social_networks' => array(
            'template' => 'tpl/social_networks',
            'path' => drupal_get_path('module', 'memory_blocks'),
            'variables' => array('infos' => NULL),
        ),
        'tpl_memory_reviews' => array(
            'template' => 'tpl/memory_reviews',
            'path' => drupal_get_path('module', 'memory_blocks'),
            'variables' => array('infos' => NULL),
        ),
        'tpl_memory_top_destinations' => array(
            'template' => 'tpl/memory_top_destinations',
            'path' => drupal_get_path('module', 'memory_blocks'),
            'variables' => array('infos' => NULL),
        ),
        'tpl_memory_top_activities' => array(
            'template' => 'tpl/memory_top_activities',
            'path' => drupal_get_path('module', 'memory_blocks'),
            'variables' => array('infos' => NULL),
        ),
        'tpl_memory_footer' => array(
            'template' => 'tpl/memory_footer',
            'path' => drupal_get_path('module', 'memory_blocks'),
            'variables' => array('infos' => NULL),
        ),
    );
}

/**
 * @return mixed
 */
function memory_blocks_block_info() {

    $blocks['social_networks'] = array(
      'info' => t('Social Networks'),
      'weight' => 1,
      'status' => 1,
      'region' => 'header_top',
      'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    );

    $blocks['memory_reviews'] = array(
      'info' => t('Memory Reviews'),
      'weight' => 2,
      'status' => 1,
      'region' => 'content',
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => '<front>',
    );

    $blocks['memory_top_destinations'] = array(
      'info' => t('Memory Top Destinations'),
      'weight' => 3,
      'status' => 1,
      'region' => 'content',
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => '<front>',
    );

    $blocks['memory_top_activities'] = array(
      'info' => t('Memory Top Activities'),
      'weight' => 4,
      'status' => 1,
      'region' => 'content',
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => '<front>',
    );

    $blocks['memory_footer'] = array(
      'info' => t('Memory Footer'),
      'weight' => 1,
      'status' => 1,
      'region' => 'footer',
      'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    );

    return $blocks;
}

/**
 * @param string $delta
 * @return array
 * @throws Exception
 */
function memory_blocks_block_view($delta = '') {

    $block = array();

    switch ($delta) {
        case 'social_networks':

            $query = db_select('memory_social_networks', 'msn');
            $query->fields('msn', array('name','url','icon'));
            $data['resultsSocialNetworks'] = $query->execute();

            // Link the template
            $block['content']['#markup'] = theme('tpl_social_networks', $data);

            // Link a css file 
            $block['content']['#attached']['css'][] = array(
                'data' => drupal_get_path('module', 'memory_blocks').'/css/social_networks.css',
                'type' => 'file'
            );

            // // Link a js file
            // $block['content']['#attached']['js'][] = array(
            //     'data' => drupal_get_path('module', 'bsconnexion').'/js/bs-cc-menu.js',
            //     'type' => 'file'
            // );

            break;
        case 'memory_reviews':

            // Link the template
            $block['content']['#markup'] = theme('tpl_memory_reviews');

            // Link a css file
            $block['content']['#attached']['css'][] = array(
                'data' => drupal_get_path('module', 'memory_blocks').'/css/memory_reviews.css',
                'type' => 'file'
            );

            break;
        case 'memory_top_destinations':

            $data['title'] = variable_get("top_destinations_title");
//            $data['description'] = variable_get("top_destinations_description");
            $description = variable_get("top_destinations_description");
            $data['description'] = $description['value'];

            /* Initialize Top destination variables */
            $top_destinations_1 = variable_get('top_destinations_1', array());
            $top_destinations_2 = variable_get('top_destinations_2', array());
            $top_destinations_3 = variable_get('top_destinations_3', array());
            $top_destinations_4 = variable_get('top_destinations_4', array());
            $top_destinations_5 = variable_get('top_destinations_5', array());
            $top_destinations_6 = variable_get('top_destinations_6', array());
            $top_destinations_7 = variable_get('top_destinations_7', array());
            $top_destinations_8 = variable_get('top_destinations_8', array());
            $top_destinations_9 = variable_get('top_destinations_9', array());

//            drupal_set_message("<pre>". print_r($top_destinations_3, true) ."</pre>");

            $arrayAll = array();

            for( $i = 1 ; $i <= 9 ; $i++ ){

                $stringArrayName = "top_destinations_" . $i;

                // Check if the array is set
                if(isset($$stringArrayName)){

                    // If the array is set, copy the variable to use its values
                    $arrayName = $$stringArrayName;

                    // Check if all of its values are filled
                    if(!empty($arrayName['name']) && !empty($arrayName['image']) && !empty($arrayName['url'])){

                        /*
                         * $arrayName['image'] correspond to the fid
                         * Load the file by its fid.
                         * Create the URL file by using the file URI
                         */
                        $file = file_load($arrayName['image']);
                        $url = file_create_url($file->uri);
                        $arrayName['image'] = $url;

                        array_push($arrayAll, $arrayName);
                    }
                }
            }

//            drupal_set_message("<pre>". print_r($arrayAll, true) ."</pre>");

            $data['arrayAllDatas'] = $arrayAll;

            // Link the template
            $block['content']['#markup'] = theme('tpl_memory_top_destinations', $data);

            // Link a css file
            $block['content']['#attached']['css'][] = array(
                'data' => drupal_get_path('module', 'memory_blocks').'/css/memory_top_destinations.css',
                'type' => 'file'
            );

            break;
        case 'memory_top_activities':

            $data['title'] = variable_get("top_activities_title");
//            $data['description'] = variable_get("top_activities_description");
            $description = variable_get("top_activities_description");
            $data['description'] = $description['value'];

            /* Initialize Top activities variables */
            $top_activities_1 = variable_get('top_activities_1', array());
            $top_activities_2 = variable_get('top_activities_2', array());
            $top_activities_3 = variable_get('top_activities_3', array());
            $top_activities_4 = variable_get('top_activities_4', array());
            $top_activities_5 = variable_get('top_activities_5', array());
            $top_activities_6 = variable_get('top_activities_6', array());
            $top_activities_7 = variable_get('top_activities_7', array());
            $top_activities_8 = variable_get('top_activities_8', array());
            $top_activities_9 = variable_get('top_activities_9', array());

            $arrayAll = array();

            for( $i = 1 ; $i <= 9 ; $i++ ){

                $stringArrayName = "top_activities_" . $i;

                // Check if the array is set
                if(isset($$stringArrayName)){

                    // If the array is set, copy the variable to use its values
                    $arrayName = $$stringArrayName;

                    // Check if all of its values are filled
                    if(!empty($arrayName['name']) && !empty($arrayName['image']) && !empty($arrayName['url'])){

                        /*
                         * $arrayName['image'] correspond to the fid
                         * Load the file by its fid.
                         * Create the URL file by using the file URI
                         */
                        $file = file_load($arrayName['image']);
                        $url = file_create_url($file->uri);
                        $arrayName['image'] = $url;

                        array_push($arrayAll, $arrayName);
                    }
                }
            }

            $data['arrayAllDatas'] = $arrayAll;

            // Link the template
            $block['content']['#markup'] = theme('tpl_memory_top_activities', $data);

            // Link a css file
            $block['content']['#attached']['css'][] = array(
                'data' => drupal_get_path('module', 'memory_blocks').'/css/memory_top_activities.css',
                'type' => 'file'
            );

            break;
        case 'memory_footer':

            /* Footer Column Society */
            $data['footer_column_1'] = variable_get("footer_column_1", array());
            $data['footer_column_1'] = $data['footer_column_1']['society']['value'];

            /* Footer Column Contact */
            $data['footer_column_2'] = variable_get("footer_column_2", array());
            $data['footer_column_2'] = $data['footer_column_2']['contact']['value'];

            /* Footer Column Communication */
            $data['footer_column_3'] = variable_get("footer_column_3", array());
            $data['footer_column_3'] = $data['footer_column_3']['communication']['value'];

            /* Footer Column You and Us */
            $data['footer_column_4'] = variable_get("footer_column_4", array());
            $data['footer_column_4'] = $data['footer_column_4']['youandus']['value'];

            /* Footer Column Certifications */
            $data['footer_column_5'] = variable_get("footer_column_5", array());
            $data['footer_column_5'] = $data['footer_column_5']['certifications']['value'];

            /* Facebook */
            $data['facebook'] = variable_get('facebook', array());
            $data['facebook_url'] = $data['facebook']['url'];
            $facebook_display_type = $data['facebook']['display_type'];

            if( $facebook_display_type == 0 ){

                $data['facebook_display_type'] = "button";
//                $data['facebook_display_height'] = "65";
            }else{

                $data['facebook_display_type'] = "button_count";
//                $data['facebook_display_height'] = "46";
            }
            $data['facebook_display_height'] = "30";

            /* Twitter */
            $data['twitter'] = variable_get('twitter', array());
            $data['twitter_url'] = $data['twitter']['url'];
            $data['twitter_display_height'] = "30";

            // Link the template
            $block['content']['#markup'] = theme('tpl_memory_footer', $data);

            // Link a css file
            $block['content']['#attached']['css'][] = array(
                'data' => drupal_get_path('module', 'memory_blocks').'/css/memory_footer.css',
                'type' => 'file'
            );

             // Link a js file
             $block['content']['#attached']['js'][] = array(
                 'data' => drupal_get_path('module', 'memory_blocks').'/js/memory_footer.js',
                 'type' => 'file'
             );

            break;
    }

    return $block;
}

function memory_blocks_top_destinations_admin_form($form, &$form_state) {

    $form['top_destinations_title'] = array(
        '#type' => 'textfield',
        '#default_value' => variable_get('top_destinations_title', 'Top destinations'),
        '#title' => t('Titre'),
        '#weight' => 1,
        '#required' => TRUE,
    );

    $description = variable_get('top_destinations_description', array('Entrer ici votre description.' => '', 'format' => NULL));

    $form['top_destinations_description'] = array(
//        '#type' => 'textarea',
        '#type' => 'text_format',
        '#format' => 'wysiwyg',
        '#default_value' => $description['value'],
//        '#default_value' => variable_get('top_destinations_description', 'Entrer ici votre description.'),
        '#title' => t('Description'),
        '#weight' => 2,
        '#required' => TRUE,
    );

    /* Top destination n°1 */
    $form['top_destinations_1'] = array(
        '#type' => 'fieldset',
        '#title' => t('Destination n°1'),
        '#weight' => 3,
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        '#tree' => TRUE
    );

    $top_destinations_1 = variable_get('top_destinations_1', array());
    $td1_name = $top_destinations_1['name'];
    $td1_image = $top_destinations_1['image'];
    $td1_url = $top_destinations_1['url'];

    $form['top_destinations_1']['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Nom'),
        '#default_value' => $td1_name,
    );
    $form['top_destinations_1']['image'] = array(
        '#type'          => 'media',
        '#title'         => 'Image',
        '#theme'         => 'media_widget', // Without that, you only get text input
        '#default_value' => $td1_image, //The fid
//        '#default_value' => variable_get('image_saved', NULL), //The fid
        '#media_options' => array(
            'global' => array(
                'file_directory'  => 'image_folder',
                'enabledPlugins'  => array( // Not needed if you want to enable all the plugins
                    'upload',
                    'media_default--media_browser_my_files'
                ),
                'file_extensions' => 'png gif jpg jpeg',
                'max_filesize'    => '2 MB',
                'uri_scheme'      => 'public',
                'types'           => array('image'),
                'schemes'         => array(
                    'public' => 'public',
                ),
            ),
        ),
    );
    $form['top_destinations_1']['url'] = array(
        '#type' => 'textfield',
        '#title' => t('URL'),
        '#default_value' => $td1_url,
    );

    /* Top destination n°2 */
    $form['top_destinations_2'] = array(
        '#type' => 'fieldset',
        '#title' => t('Destination n°2'),
        '#weight' => 4,
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        '#tree' => TRUE
    );

    $top_destinations_2 = variable_get('top_destinations_2', array());
    $td2_name = $top_destinations_2['name'];
    $td2_image = $top_destinations_2['image'];
    $td2_url = $top_destinations_2['url'];

    $form['top_destinations_2']['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Nom'),
        '#default_value' => $td2_name,
    );
    $form['top_destinations_2']['image'] = array(
        '#type'          => 'media',
        '#title'         => 'Image',
        '#theme'         => 'media_widget', // Without that, you only get text input
        '#default_value' => $td2_image, //The fid
        '#media_options' => array(
            'global' => array(
                'file_directory'  => 'image_folder',
                'enabledPlugins'  => array( // Not needed if you want to enable all the plugins
                    'upload',
                    'media_default--media_browser_my_files'
                ),
                'file_extensions' => 'png gif jpg jpeg',
                'max_filesize'    => '2 MB',
                'uri_scheme'      => 'public',
                'types'           => array('image'),
                'schemes'         => array(
                    'public' => 'public',
                ),
            ),
        ),
    );
    $form['top_destinations_2']['url'] = array(
        '#type' => 'textfield',
        '#title' => t('URL'),
        '#default_value' => $td2_url,
    );


    /* Top destination n°3 */
    $form['top_destinations_3'] = array(
        '#type' => 'fieldset',
        '#title' => t('Destination n°3'),
        '#weight' => 5,
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        '#tree' => TRUE
    );

    $top_destinations_3 = variable_get('top_destinations_3', array());
    $td3_name = $top_destinations_3['name'];
    $td3_image = $top_destinations_3['image'];
    $td3_url = $top_destinations_3['url'];

    $form['top_destinations_3']['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Nom'),
        '#default_value' => $td3_name,
    );
    $form['top_destinations_3']['image'] = array(
        '#type'          => 'media',
        '#title'         => 'Image',
        '#theme'         => 'media_widget', // Without that, you only get text input
        '#default_value' => $td3_image, //The fid
        '#media_options' => array(
            'global' => array(
                'file_directory'  => 'image_folder',
                'enabledPlugins'  => array( // Not needed if you want to enable all the plugins
                    'upload',
                    'media_default--media_browser_my_files'
                ),
                'file_extensions' => 'png gif jpg jpeg',
                'max_filesize'    => '2 MB',
                'uri_scheme'      => 'public',
                'types'           => array('image'),
                'schemes'         => array(
                    'public' => 'public',
                ),
            ),
        ),
    );
    $form['top_destinations_3']['url'] = array(
        '#type' => 'textfield',
        '#title' => t('URL'),
        '#default_value' => $td3_url,
    );

    /* Top destination n°4 */
    $form['top_destinations_4'] = array(
        '#type' => 'fieldset',
        '#title' => t('Destination n°4'),
        '#weight' => 6,
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        '#tree' => TRUE
    );

    $top_destinations_4 = variable_get('top_destinations_4', array());
    $td4_name = $top_destinations_4['name'];
    $td4_image = $top_destinations_4['image'];
    $td4_url = $top_destinations_4['url'];

    $form['top_destinations_4']['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Nom'),
        '#default_value' => $td4_name,
    );
    $form['top_destinations_4']['image'] = array(
        '#type'          => 'media',
        '#title'         => 'Image',
        '#theme'         => 'media_widget', // Without that, you only get text input
        '#default_value' => $td4_image, //The fid
        '#media_options' => array(
            'global' => array(
                'file_directory'  => 'image_folder',
                'enabledPlugins'  => array( // Not needed if you want to enable all the plugins
                    'upload',
                    'media_default--media_browser_my_files'
                ),
                'file_extensions' => 'png gif jpg jpeg',
                'max_filesize'    => '2 MB',
                'uri_scheme'      => 'public',
                'types'           => array('image'),
                'schemes'         => array(
                    'public' => 'public',
                ),
            ),
        ),
    );
    $form['top_destinations_4']['url'] = array(
        '#type' => 'textfield',
        '#title' => t('URL'),
        '#default_value' => $td4_url,
    );

    /* Top destination n°5 */
    $form['top_destinations_5'] = array(
        '#type' => 'fieldset',
        '#title' => t('Destination n°5'),
        '#weight' => 7,
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        '#tree' => TRUE
    );

    $top_destinations_5 = variable_get('top_destinations_5', array());
    $td5_name = $top_destinations_5['name'];
    $td5_image = $top_destinations_5['image'];
    $td5_url = $top_destinations_5['url'];

    $form['top_destinations_5']['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Nom'),
        '#default_value' => $td5_name,
    );
    $form['top_destinations_5']['image'] = array(
        '#type'          => 'media',
        '#title'         => 'Image',
        '#theme'         => 'media_widget', // Without that, you only get text input
        '#default_value' => $td5_image, //The fid
        '#media_options' => array(
            'global' => array(
                'file_directory'  => 'image_folder',
                'enabledPlugins'  => array( // Not needed if you want to enable all the plugins
                    'upload',
                    'media_default--media_browser_my_files'
                ),
                'file_extensions' => 'png gif jpg jpeg',
                'max_filesize'    => '2 MB',
                'uri_scheme'      => 'public',
                'types'           => array('image'),
                'schemes'         => array(
                    'public' => 'public',
                ),
            ),
        ),
    );
    $form['top_destinations_5']['url'] = array(
        '#type' => 'textfield',
        '#title' => t('URL'),
        '#default_value' => $td5_url,
    );

    /* Top destination n°6 */
    $form['top_destinations_6'] = array(
        '#type' => 'fieldset',
        '#title' => t('Destination n°6'),
        '#weight' => 8,
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        '#tree' => TRUE
    );

    $top_destinations_6 = variable_get('top_destinations_6', array());
    $td6_name = $top_destinations_6['name'];
    $td6_image = $top_destinations_6['image'];
    $td6_url = $top_destinations_6['url'];

    $form['top_destinations_6']['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Nom'),
        '#default_value' => $td6_name,
    );
    $form['top_destinations_6']['image'] = array(
        '#type'          => 'media',
        '#title'         => 'Image',
        '#theme'         => 'media_widget', // Without that, you only get text input
        '#default_value' => $td6_image, //The fid
        '#media_options' => array(
            'global' => array(
                'file_directory'  => 'image_folder',
                'enabledPlugins'  => array( // Not needed if you want to enable all the plugins
                    'upload',
                    'media_default--media_browser_my_files'
                ),
                'file_extensions' => 'png gif jpg jpeg',
                'max_filesize'    => '2 MB',
                'uri_scheme'      => 'public',
                'types'           => array('image'),
                'schemes'         => array(
                    'public' => 'public',
                ),
            ),
        ),
    );
    $form['top_destinations_6']['url'] = array(
        '#type' => 'textfield',
        '#title' => t('URL'),
        '#default_value' => $td6_url,
    );

    /* Top destination n°7 */
    $form['top_destinations_7'] = array(
        '#type' => 'fieldset',
        '#title' => t('Destination n°7'),
        '#weight' => 9,
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        '#tree' => TRUE
    );

    $top_destinations_7 = variable_get('top_destinations_7', array());
    $td7_name = $top_destinations_7['name'];
    $td7_image = $top_destinations_7['image'];
    $td7_url = $top_destinations_7['url'];

    $form['top_destinations_7']['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Nom'),
        '#default_value' => $td7_name,
    );
    $form['top_destinations_7']['image'] = array(
        '#type'          => 'media',
        '#title'         => 'Image',
        '#theme'         => 'media_widget', // Without that, you only get text input
        '#default_value' => $td7_image, //The fid
        '#media_options' => array(
            'global' => array(
                'file_directory'  => 'image_folder',
                'enabledPlugins'  => array( // Not needed if you want to enable all the plugins
                    'upload',
                    'media_default--media_browser_my_files'
                ),
                'file_extensions' => 'png gif jpg jpeg',
                'max_filesize'    => '2 MB',
                'uri_scheme'      => 'public',
                'types'           => array('image'),
                'schemes'         => array(
                    'public' => 'public',
                ),
            ),
        ),
    );
    $form['top_destinations_7']['url'] = array(
        '#type' => 'textfield',
        '#title' => t('URL'),
        '#default_value' => $td7_url,
    );

    /* Top destination n°8 */
    $form['top_destinations_8'] = array(
        '#type' => 'fieldset',
        '#title' => t('Destination n°8'),
        '#weight' => 10,
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        '#tree' => TRUE
    );

    $top_destinations_8 = variable_get('top_destinations_8', array());
    $td8_name = $top_destinations_8['name'];
    $td8_image = $top_destinations_8['image'];
    $td8_url = $top_destinations_8['url'];

    $form['top_destinations_8']['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Nom'),
        '#default_value' => $td8_name,
    );
    $form['top_destinations_8']['image'] = array(
        '#type'          => 'media',
        '#title'         => 'Image',
        '#theme'         => 'media_widget', // Without that, you only get text input
        '#default_value' => $td8_image, //The fid
        '#media_options' => array(
            'global' => array(
                'file_directory'  => 'image_folder',
                'enabledPlugins'  => array( // Not needed if you want to enable all the plugins
                    'upload',
                    'media_default--media_browser_my_files'
                ),
                'file_extensions' => 'png gif jpg jpeg',
                'max_filesize'    => '2 MB',
                'uri_scheme'      => 'public',
                'types'           => array('image'),
                'schemes'         => array(
                    'public' => 'public',
                ),
            ),
        ),
    );
    $form['top_destinations_8']['url'] = array(
        '#type' => 'textfield',
        '#title' => t('URL'),
        '#default_value' => $td8_url,
    );

    /* Top destination n°9 */
    $form['top_destinations_9'] = array(
        '#type' => 'fieldset',
        '#title' => t('Destination n°9'),
        '#weight' => 11,
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        '#tree' => TRUE
    );

    $top_destinations_9 = variable_get('top_destinations_9', array());
    $td9_name = $top_destinations_9['name'];
    $td9_image = $top_destinations_9['image'];
    $td9_url = $top_destinations_9['url'];

    $form['top_destinations_9']['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Nom'),
        '#default_value' => $td9_name,
    );
    $form['top_destinations_9']['image'] = array(
        '#type'          => 'media',
        '#title'         => 'Image',
        '#theme'         => 'media_widget', // Without that, you only get text input
        '#default_value' => $td9_image, //The fid
        '#media_options' => array(
            'global' => array(
                'file_directory'  => 'image_folder',
                'enabledPlugins'  => array( // Not needed if you want to enable all the plugins
                    'upload',
                    'media_default--media_browser_my_files'
                ),
                'file_extensions' => 'png gif jpg jpeg',
                'max_filesize'    => '2 MB',
                'uri_scheme'      => 'public',
                'types'           => array('image'),
                'schemes'         => array(
                    'public' => 'public',
                ),
            ),
        ),
    );
    $form['top_destinations_9']['url'] = array(
        '#type' => 'textfield',
        '#title' => t('URL'),
        '#default_value' => $td9_url,
    );

    return system_settings_form($form);
}

function memory_blocks_top_activities_admin_form($form, &$form_state) {

    $form['top_activities_title'] = array(
        '#type' => 'textfield',
        '#default_value' => variable_get('top_activities_title', 'Top activités'),
        '#title' => t('Titre'),
        '#weight' => 1,
        '#required' => TRUE,
    );

    $description = variable_get('top_activities_description', array('Entrer ici votre description.' => '', 'format' => NULL));

    $form['top_activities_description'] = array(
//        '#type' => 'textarea',
        '#type' => 'text_format',
        '#format' => 'wysiwyg',
        '#default_value' => $description['value'],
//        '#default_value' => variable_get('top_activities_description', 'Entrer ici votre description.'),
        '#title' => t('Description'),
        '#weight' => 2,
        '#required' => TRUE,
    );

    /* Top activity n°1 */
    $form['top_activities_1'] = array(
        '#type' => 'fieldset',
        '#title' => t('Activity n°1'),
        '#weight' => 3,
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        '#tree' => TRUE
    );

    $top_activities_1 = variable_get('top_activities_1', array());
    $ta1_name = $top_activities_1['name'];
    $ta1_image = $top_activities_1['image'];
    $ta1_url = $top_activities_1['url'];

    $form['top_activities_1']['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Nom'),
        '#default_value' => $ta1_name,
    );
    $form['top_activities_1']['image'] = array(
        '#type'          => 'media',
        '#title'         => 'Image',
        '#theme'         => 'media_widget', // Without that, you only get text input
        '#default_value' => $ta1_image, //The fid
//        '#default_value' => variable_get('image_saved', NULL), //The fid
        '#media_options' => array(
            'global' => array(
                'file_directory'  => 'image_folder',
//                'enabledPlugins'  => array( // Not needed if you want to enable all the plugins
//                    'upload',
//                    'media_default--media_browser_my_files'
//                ),
                'file_extensions' => 'png gif jpg jpeg',
                'max_filesize'    => '2 MB',
                'uri_scheme'      => 'public',
                'types'           => array('image'),
                'schemes'         => array(
                    'public' => 'public',
                ),
            ),
        ),
    );
    $form['top_activities_1']['url'] = array(
        '#type' => 'textfield',
        '#title' => t('URL'),
        '#default_value' => $ta1_url,
    );

    /* Top activity n°2 */
    $form['top_activities_2'] = array(
        '#type' => 'fieldset',
        '#title' => t('Activity n°2'),
        '#weight' => 4,
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        '#tree' => TRUE
    );

    $top_activities_2 = variable_get('top_activities_2', array());
    $ta2_name = $top_activities_2['name'];
    $ta2_image = $top_activities_2['image'];
    $ta2_url = $top_activities_2['url'];

    $form['top_activities_2']['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Nom'),
        '#default_value' => $ta2_name,
    );
    $form['top_activities_2']['image'] = array(
        '#type'          => 'media',
        '#title'         => 'Image',
        '#theme'         => 'media_widget', // Without that, you only get text input
        '#default_value' => $ta2_image, //The fid
        '#media_options' => array(
            'global' => array(
                'file_directory'  => 'image_folder',
                'enabledPlugins'  => array( // Not needed if you want to enable all the plugins
                    'upload',
                    'media_default--media_browser_my_files'
                ),
                'file_extensions' => 'png gif jpg jpeg',
                'max_filesize'    => '2 MB',
                'uri_scheme'      => 'public',
                'types'           => array('image'),
                'schemes'         => array(
                    'public' => 'public',
                ),
            ),
        ),
    );
    $form['top_activities_2']['url'] = array(
        '#type' => 'textfield',
        '#title' => t('URL'),
        '#default_value' => $ta2_url,
    );


    /* Top activity n°3 */
    $form['top_activities_3'] = array(
        '#type' => 'fieldset',
        '#title' => t('Activity n°3'),
        '#weight' => 5,
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        '#tree' => TRUE
    );

    $top_activities_3 = variable_get('top_activities_3', array());
    $ta3_name = $top_activities_3['name'];
    $ta3_image = $top_activities_3['image'];
    $ta3_url = $top_activities_3['url'];

    $form['top_activities_3']['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Nom'),
        '#default_value' => $ta3_name,
    );
    $form['top_activities_3']['image'] = array(
        '#type'          => 'media',
        '#title'         => 'Image',
        '#theme'         => 'media_widget', // Without that, you only get text input
        '#default_value' => $ta3_image, //The fid
        '#media_options' => array(
            'global' => array(
                'file_directory'  => 'image_folder',
                'enabledPlugins'  => array( // Not needed if you want to enable all the plugins
                    'upload',
                    'media_default--media_browser_my_files'
                ),
                'file_extensions' => 'png gif jpg jpeg',
                'max_filesize'    => '2 MB',
                'uri_scheme'      => 'public',
                'types'           => array('image'),
                'schemes'         => array(
                    'public' => 'public',
                ),
            ),
        ),
    );
    $form['top_activities_3']['url'] = array(
        '#type' => 'textfield',
        '#title' => t('URL'),
        '#default_value' => $ta3_url,
    );

    /* Top activity n°4 */
    $form['top_activities_4'] = array(
        '#type' => 'fieldset',
        '#title' => t('Activity n°4'),
        '#weight' => 6,
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        '#tree' => TRUE
    );

    $top_activities_4 = variable_get('top_activities_4', array());
    $ta4_name = $top_activities_4['name'];
    $ta4_image = $top_activities_4['image'];
    $ta4_url = $top_activities_4['url'];

    $form['top_activities_4']['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Nom'),
        '#default_value' => $ta4_name,
    );
    $form['top_activities_4']['image'] = array(
        '#type'          => 'media',
        '#title'         => 'Image',
        '#theme'         => 'media_widget', // Without that, you only get text input
        '#default_value' => $ta4_image, //The fid
        '#media_options' => array(
            'global' => array(
                'file_directory'  => 'image_folder',
                'enabledPlugins'  => array( // Not needed if you want to enable all the plugins
                    'upload',
                    'media_default--media_browser_my_files'
                ),
                'file_extensions' => 'png gif jpg jpeg',
                'max_filesize'    => '2 MB',
                'uri_scheme'      => 'public',
                'types'           => array('image'),
                'schemes'         => array(
                    'public' => 'public',
                ),
            ),
        ),
    );
    $form['top_activities_4']['url'] = array(
        '#type' => 'textfield',
        '#title' => t('URL'),
        '#default_value' => $ta4_url,
    );

    /* Top activity n°5 */
    $form['top_activities_5'] = array(
        '#type' => 'fieldset',
        '#title' => t('Activity n°5'),
        '#weight' => 7,
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        '#tree' => TRUE
    );

    $top_activities_5 = variable_get('top_activities_5', array());
    $ta5_name = $top_activities_5['name'];
    $ta5_image = $top_activities_5['image'];
    $ta5_url = $top_activities_5['url'];

    $form['top_activities_5']['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Nom'),
        '#default_value' => $ta5_name,
    );
    $form['top_activities_5']['image'] = array(
        '#type'          => 'media',
        '#title'         => 'Image',
        '#theme'         => 'media_widget', // Without that, you only get text input
        '#default_value' => $ta5_image, //The fid
        '#media_options' => array(
            'global' => array(
                'file_directory'  => 'image_folder',
                'enabledPlugins'  => array( // Not needed if you want to enable all the plugins
                    'upload',
                    'media_default--media_browser_my_files'
                ),
                'file_extensions' => 'png gif jpg jpeg',
                'max_filesize'    => '2 MB',
                'uri_scheme'      => 'public',
                'types'           => array('image'),
                'schemes'         => array(
                    'public' => 'public',
                ),
            ),
        ),
    );
    $form['top_activities_5']['url'] = array(
        '#type' => 'textfield',
        '#title' => t('URL'),
        '#default_value' => $ta5_url,
    );

    /* Top activity n°6 */
    $form['top_activities_6'] = array(
        '#type' => 'fieldset',
        '#title' => t('Activity n°6'),
        '#weight' => 8,
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        '#tree' => TRUE
    );

    $top_activities_6 = variable_get('top_activities_6', array());
    $ta6_name = $top_activities_6['name'];
    $ta6_image = $top_activities_6['image'];
    $ta6_url = $top_activities_6['url'];

    $form['top_activities_6']['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Nom'),
        '#default_value' => $ta6_name,
    );
    $form['top_activities_6']['image'] = array(
        '#type'          => 'media',
        '#title'         => 'Image',
        '#theme'         => 'media_widget', // Without that, you only get text input
        '#default_value' => $ta6_image, //The fid
        '#media_options' => array(
            'global' => array(
                'file_directory'  => 'image_folder',
                'enabledPlugins'  => array( // Not needed if you want to enable all the plugins
                    'upload',
                    'media_default--media_browser_my_files'
                ),
                'file_extensions' => 'png gif jpg jpeg',
                'max_filesize'    => '2 MB',
                'uri_scheme'      => 'public',
                'types'           => array('image'),
                'schemes'         => array(
                    'public' => 'public',
                ),
            ),
        ),
    );
    $form['top_activities_6']['url'] = array(
        '#type' => 'textfield',
        '#title' => t('URL'),
        '#default_value' => $ta6_url,
    );

    /* Top activity n°7 */
    $form['top_activities_7'] = array(
        '#type' => 'fieldset',
        '#title' => t('Activity n°7'),
        '#weight' => 9,
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        '#tree' => TRUE
    );

    $top_activities_7 = variable_get('top_activities_7', array());
    $ta7_name = $top_activities_7['name'];
    $ta7_image = $top_activities_7['image'];
    $ta7_url = $top_activities_7['url'];

    $form['top_activities_7']['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Nom'),
        '#default_value' => $ta7_name,
    );
    $form['top_activities_7']['image'] = array(
        '#type'          => 'media',
        '#title'         => 'Image',
        '#theme'         => 'media_widget', // Without that, you only get text input
        '#default_value' => $ta7_image, //The fid
        '#media_options' => array(
            'global' => array(
                'file_directory'  => 'image_folder',
                'enabledPlugins'  => array( // Not needed if you want to enable all the plugins
                    'upload',
                    'media_default--media_browser_my_files'
                ),
                'file_extensions' => 'png gif jpg jpeg',
                'max_filesize'    => '2 MB',
                'uri_scheme'      => 'public',
                'types'           => array('image'),
                'schemes'         => array(
                    'public' => 'public',
                ),
            ),
        ),
    );
    $form['top_activities_7']['url'] = array(
        '#type' => 'textfield',
        '#title' => t('URL'),
        '#default_value' => $ta7_url,
    );

    /* Top activity n°8 */
    $form['top_activities_8'] = array(
        '#type' => 'fieldset',
        '#title' => t('Activity n°8'),
        '#weight' => 10,
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        '#tree' => TRUE
    );

    $top_activities_8 = variable_get('top_activities_8', array());
    $ta8_name = $top_activities_8['name'];
    $ta8_image = $top_activities_8['image'];
    $ta8_url = $top_activities_8['url'];

    $form['top_activities_8']['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Nom'),
        '#default_value' => $ta8_name,
    );
    $form['top_activities_8']['image'] = array(
        '#type'          => 'media',
        '#title'         => 'Image',
        '#theme'         => 'media_widget', // Without that, you only get text input
        '#default_value' => $ta8_image, //The fid
        '#media_options' => array(
            'global' => array(
                'file_directory'  => 'image_folder',
                'enabledPlugins'  => array( // Not needed if you want to enable all the plugins
                    'upload',
                    'media_default--media_browser_my_files'
                ),
                'file_extensions' => 'png gif jpg jpeg',
                'max_filesize'    => '2 MB',
                'uri_scheme'      => 'public',
                'types'           => array('image'),
                'schemes'         => array(
                    'public' => 'public',
                ),
            ),
        ),
    );
    $form['top_activities_8']['url'] = array(
        '#type' => 'textfield',
        '#title' => t('URL'),
        '#default_value' => $ta8_url,
    );

    /* Top activity n°9 */
    $form['top_activities_9'] = array(
        '#type' => 'fieldset',
        '#title' => t('Activity n°9'),
        '#weight' => 11,
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        '#tree' => TRUE
    );

    $top_activities_9 = variable_get('top_activities_9', array());
    $ta9_name = $top_activities_9['name'];
    $ta9_image = $top_activities_9['image'];
    $ta9_url = $top_activities_9['url'];

    $form['top_activities_9']['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Nom'),
        '#default_value' => $ta9_name,
    );
    $form['top_activities_9']['image'] = array(
        '#type'          => 'media',
        '#title'         => 'Image',
        '#theme'         => 'media_widget', // Without that, you only get text input
        '#default_value' => $ta9_image, //The fid
        '#media_options' => array(
            'global' => array(
                'file_directory'  => 'image_folder',
                'enabledPlugins'  => array( // Not needed if you want to enable all the plugins
                    'upload',
                    'media_default--media_browser_my_files'
                ),
                'file_extensions' => 'png gif jpg jpeg',
                'max_filesize'    => '2 MB',
                'uri_scheme'      => 'public',
                'types'           => array('image'),
                'schemes'         => array(
                    'public' => 'public',
                ),
            ),
        ),
    );
    $form['top_activities_9']['url'] = array(
        '#type' => 'textfield',
        '#title' => t('URL'),
        '#default_value' => $ta9_url,
    );

    /* Top activity n°10 */
    $form['top_activities_10'] = array(
        '#type' => 'fieldset',
        '#title' => t('Activity n°10'),
        '#weight' => 12,
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        '#tree' => TRUE
    );

    $top_activities_10 = variable_get('top_activities_10', array());
    $ta10_name = $top_activities_10['name'];
    $ta10_image = $top_activities_10['image'];
    $ta10_url = $top_activities_10['url'];

    $form['top_activities_10']['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Nom'),
        '#default_value' => $ta10_name,
    );
    $form['top_activities_10']['image'] = array(
        '#type'          => 'media',
        '#title'         => 'Image',
        '#theme'         => 'media_widget', // Without that, you only get text input
        '#default_value' => $ta10_image, //The fid
        '#media_options' => array(
            'global' => array(
                'file_directory'  => 'image_folder',
                'enabledPlugins'  => array( // Not needed if you want to enable all the plugins
                    'upload',
                    'media_default--media_browser_my_files'
                ),
                'file_extensions' => 'png gif jpg jpeg',
                'max_filesize'    => '2 MB',
                'uri_scheme'      => 'public',
                'types'           => array('image'),
                'schemes'         => array(
                    'public' => 'public',
                ),
            ),
        ),
    );
    $form['top_activities_10']['url'] = array(
        '#type' => 'textfield',
        '#title' => t('URL'),
        '#default_value' => $ta10_url,
    );

    /* Top activity n°11 */
    $form['top_activities_11'] = array(
        '#type' => 'fieldset',
        '#title' => t('Activity n°11'),
        '#weight' => 13,
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        '#tree' => TRUE
    );

    $top_activities_11 = variable_get('top_activities_11', array());
    $ta11_name = $top_activities_11['name'];
    $ta11_image = $top_activities_11['image'];
    $ta11_url = $top_activities_11['url'];

    $form['top_activities_11']['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Nom'),
        '#default_value' => $ta11_name,
    );
    $form['top_activities_11']['image'] = array(
        '#type'          => 'media',
        '#title'         => 'Image',
        '#theme'         => 'media_widget', // Without that, you only get text input
        '#default_value' => $ta11_image, //The fid
        '#media_options' => array(
            'global' => array(
                'file_directory'  => 'image_folder',
                'enabledPlugins'  => array( // Not needed if you want to enable all the plugins
                    'upload',
                    'media_default--media_browser_my_files'
                ),
                'file_extensions' => 'png gif jpg jpeg',
                'max_filesize'    => '2 MB',
                'uri_scheme'      => 'public',
                'types'           => array('image'),
                'schemes'         => array(
                    'public' => 'public',
                ),
            ),
        ),
    );
    $form['top_activities_11']['url'] = array(
        '#type' => 'textfield',
        '#title' => t('URL'),
        '#default_value' => $ta11_url,
    );

    /* Top activity n°12 */
    $form['top_activities_12'] = array(
        '#type' => 'fieldset',
        '#title' => t('Activity n°12'),
        '#weight' => 14,
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        '#tree' => TRUE
    );

    $top_activities_12 = variable_get('top_activities_12', array());
    $ta12_name = $top_activities_12['name'];
    $ta12_image = $top_activities_12['image'];
    $ta12_url = $top_activities_12['url'];

    $form['top_activities_12']['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Nom'),
        '#default_value' => $ta12_name,
    );
    $form['top_activities_12']['image'] = array(
        '#type'          => 'media',
        '#title'         => 'Image',
        '#theme'         => 'media_widget', // Without that, you only get text input
        '#default_value' => $ta12_image, //The fid
        '#media_options' => array(
            'global' => array(
                'file_directory'  => 'image_folder',
                'enabledPlugins'  => array( // Not needed if you want to enable all the plugins
                    'upload',
                    'media_default--media_browser_my_files'
                ),
                'file_extensions' => 'png gif jpg jpeg',
                'max_filesize'    => '2 MB',
                'uri_scheme'      => 'public',
                'types'           => array('image'),
                'schemes'         => array(
                    'public' => 'public',
                ),
            ),
        ),
    );
    $form['top_activities_12']['url'] = array(
        '#type' => 'textfield',
        '#title' => t('URL'),
        '#default_value' => $ta12_url,
    );

    return system_settings_form($form);
}

function memory_blocks_footer_admin_form($form, &$form_state) {

    /* Society Column */
    $form['footer_column_1'] = array(
        '#type' => 'fieldset',
        '#title' => t('Colonne Société'),
        '#weight' => 1,
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
        '#tree' => TRUE
    );

    $footer_column_1 = variable_get('footer_column_1', array());

    $form['footer_column_1']['society'] = array(
        '#type' => 'text_format',
        '#format' => 'wysiwyg',
        '#default_value' => $footer_column_1['society']['value'],
        '#title' => t('Société'),
        '#weight' => 1,
    );

    /* Contact Column */
    $form['footer_column_2'] = array(
        '#type' => 'fieldset',
        '#title' => t('Colonne Contact'),
        '#weight' => 2,
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
        '#tree' => TRUE
    );

    $footer_column_2 = variable_get('footer_column_2', array());

    $form['footer_column_2']['contact'] = array(
        '#type' => 'text_format',
        '#format' => 'wysiwyg',
        '#default_value' => $footer_column_2['contact']['value'],
        '#title' => t('Contact'),
        '#weight' => 1,
    );

    /* Communication Column */
    $form['footer_column_3'] = array(
        '#type' => 'fieldset',
        '#title' => t('Colonne Communication'),
        '#weight' => 3,
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
        '#tree' => TRUE
    );

    $footer_column_3 = variable_get('footer_column_3', array());

    $form['footer_column_3']['communication'] = array(
        '#type' => 'text_format',
        '#format' => 'wysiwyg',
        '#default_value' => $footer_column_3['communication']['value'],
        '#title' => t('Communication'),
        '#weight' => 1,
    );

    /* You and Us Column */
    $form['footer_column_4'] = array(
        '#type' => 'fieldset',
        '#title' => t('Colonne Vous et Nous'),
        '#weight' => 4,
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
        '#tree' => TRUE
    );

    $footer_column_4 = variable_get('footer_column_4', array());

    $form['footer_column_4']['youandus'] = array(
        '#type' => 'text_format',
        '#format' => 'wysiwyg',
        '#default_value' => $footer_column_4['youandus']['value'],
        '#title' => t('Vous et Nous'),
        '#weight' => 1,
    );

    /* Certifications Column */
    $form['footer_column_5'] = array(
        '#type' => 'fieldset',
        '#title' => t('Colonne Certifications'),
        '#weight' => 5,
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
        '#tree' => TRUE
    );

    $footer_column_5 = variable_get('footer_column_5', array());

    $form['footer_column_5']['certifications'] = array(
        '#type' => 'text_format',
        '#format' => 'wysiwyg',
        '#default_value' => $footer_column_5['certifications']['value'],
        '#title' => t('Certifications'),
        '#weight' => 1,
    );

    /* Facebook Likes and Shares */
    $form['facebook'] = array(
        '#type' => 'fieldset',
        '#title' => t('Facebook'),
        '#weight' => 6,
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
        '#tree' => TRUE
    );

    $facebook = variable_get('facebook', array());

    $form['facebook']['url'] = array(
        '#type' => 'textfield',
        '#default_value' => $facebook['url'],
        '#title' => t('URL'),
        '#description' => t('Renseignez la partie de l\'URL correspondant à votre page Facebook.<br>Exemple : Pour l\'URL https://www.facebook.com/FacebookFrance/ , renseignez seulement FacebookFrance'),
        '#weight' => 1,
    );

    $form['facebook']['display_type'] = array(
        '#type' => 'radios',
        '#title' => t('Type d\'affichage'),
        '#default_value' => $facebook['display_type'],
        '#options' => array(
            0 => t('Sans le nombre de likes'),
            1 => t('Avec le nombre de likes')
        ),
        '#description' => t('Choix de l\'affichage pour le bouton j\'aime de Facebook.'),
        '#weight' => 2,
    );

    /* Twitter Tweets */
    $form['twitter'] = array(
        '#type' => 'fieldset',
        '#title' => t('Twitter'),
        '#weight' => 7,
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
        '#tree' => TRUE
    );

    $twitter = variable_get('twitter', array());

    $form['twitter']['url'] = array(
        '#type' => 'textfield',
        '#default_value' => $twitter['url'],
        '#title' => t('URL'),
        '#description' => t('Renseignez la partie de l\'URL correspondant à votre page Twitter.<br>Exemple : Pour l\'URL https://twitter.com/twitter , renseignez seulement twitter'),
        '#weight' => 1,
    );

    return system_settings_form($form);
}
