<?php

/**
* Implementation of hook_menu()
*
* @return array
*/
function memory_map_menu() {
    $items = array();

//    $items['map'] = array(
//        'title' => t('Memory map'),
//        'description' => t('Memory - map'),
//        'page callback' => 'memory_map_block_view',
//        'access callback' => TRUE,
//        'type' => MENU_NORMAL_ITEM,
//    );

    $items['admin/memory/map-manager'] = array(
        'title' => t('Memory - World map'),
        'description' => t('Memory - World map manager'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('memory_blocks_world_map_admin_form'),
        'access arguments' => array('administer site configuration'),
        'type' => MENU_NORMAL_ITEM,
    );

    return $items;
}

function memory_map_init(){
//    drupal_add_library('system','ui.dialog');
//    drupal_add_js(drupal_get_path('module', 'memory_map') . '/js/jquery-ui-1.12.1/jquery-ui.js');
}

/**
 * Implement hook_theme()
 *
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function memory_map_theme($existing, $type, $theme, $path) {
    return array(
        'tpl_memory_map' => array(
            'template' => 'tpl/memory_map',
            'path' => drupal_get_path('module', 'memory_map'),
            'variables' => array('infos' => NULL),
        ),
    );
}

/**
 * @return mixed
 */
function memory_map_block_info() {

    $blocks['memory_map'] = array(
        'info' => t('Memory map'),
        'weight' => 5,
        'status' => 1,
        'region' => 'content',
        'visibility' => BLOCK_VISIBILITY_LISTED,
        'pages' => '<front>',
//        'pages' => 'map',
    );

    return $blocks;
}

/**
 * @param string $delta
 * @return array
 * @throws Exception
 */
function memory_map_block_view($delta = '') {

    $block = array();

    switch ($delta) {
        case 'memory_map':

            $data["world_map_title"] = variable_get("world_map_title");
            $world_map_description = variable_get("world_map_description");
            $data["world_map_description"] = $world_map_description["value"];

            // Link the template
            $block['content']['#markup'] = theme('tpl_memory_map', $data);

            // Link a css file
            $block['content']['#attached']['css'][] = array(
                'data' => drupal_get_path('module', 'memory_map').'/css/memory_map.css',
                'type' => 'file'
            );

             // Link a js file
             $block['content']['#attached']['js'][] = array(
                 'data' => drupal_get_path('module', 'memory_map').'/js/memory_map.js',
                 'type' => 'file'
             );

            break;
    }

    return $block;
}

function memory_blocks_world_map_admin_form($form, &$form_state){

    $form['world_map_title'] = array(
        '#type' => 'textfield',
        '#default_value' => variable_get('world_map_title', ''),
        '#title' => t('Titre'),
        '#weight' => 1,
    );

    $description = variable_get('world_map_description', array('' => '', 'format' => NULL));

    $form['world_map_description'] = array(
        '#type' => 'text_format',
        '#format' => 'wysiwyg',
        '#default_value' => $description['value'],
        '#title' => t('Description'),
        '#weight' => 2,
    );

    return system_settings_form($form);
}